#!/usr/bin/env python
from abc import abstractmethod
import os

import torch.nn as nn
import torch
from equiv_networks.trainer import Trainer

class BaseModel:

    def __init__(self, network, dims, network_parameters={}, trainer=Trainer,
                 parameters_trainer={}):

        self.network = network(dims=dims, **network_parameters).double()
        self.trainer = trainer(self, **parameters_trainer)
        self.path = None

    def train(self, parameters_training={}):
        return self.trainer.train(**parameters_training)

    def save_neural_network(self, path=None):
        if path is None:
            if self.path is None:
                import time
                time_string = time.strftime("%Y%m%d-%H%M%S")
                path = "torch-model-" + time_string + ".pt"
                self.path = path
        else:
            self.path = path

        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        torch.save(self.network.state_dict(), self.path)


    def load_neural_network(self, path=None):
        if path is None:
            self.network.load_state_dict(torch.load(self.path))
        else:
            self.network.load_state_dict(torch.load(path, map_location=torch.device("cpu")))



class NonlinearManifoldsMOR2D(BaseModel):
    """Class that implements the approach using nonlinear manifolds generated by convolutional autoencoders.

    Parameters
    ----------
    network
        Neural network class to use for the autoencoder.
    scaler
        Scaler object used to scale the data before training and unscale the predictions.
    dims
        Tuple of dimensions of the full-order model (e.g. (2, Nx, Ny)).
    network_parameters
        Additional parameters used to create the neural network.
    trainer
          Trainer to use for the neural network.
    parameters_trainer
        Additional parameters used to create the Trainer.
    loss_function
        Loss function to use in the training of the neural network.
    """

    def __init__(self, 
                 network=None,
                 scaler=None,
                 dims=None,
                 network_parameters=None,
                 trainer=Trainer,
                 parameters_trainer={}, 
                 loss_function=nn.MSELoss()):

        super().__init__(network=network, dims=dims, network_parameters=network_parameters, trainer=trainer,
                         parameters_trainer=parameters_trainer)
        
        self.scaler = scaler
        self.dims = dims
        self.loss_function = loss_function
        self.save_checkpoint = True